Prathamesh Ingale

# Practical 2.5 Scikit Learn

## Aim:
Introduction to Python Programming: Scikit Learn

## Theory:

### Scikit Learn
Scikit-learn is a free software machine learning library for the Python programming language. It features various classification, regression and clustering algorithms including support vector machines, random forests, gradient boosting, k-means and DBSCAN, and is designed to interoperate with the Python numerical and scientific libraries NumPy and SciPy.

Here are some key features and functionalities of scikit-learn:

1. Supervised learning algorithms: Scikit-learn includes a variety of supervised learning algorithms, including linear regression, logistic regression, decision trees, random forests, support vector machines (SVM), and naive Bayes classifiers. These algorithms can be used for tasks such as classification and regression.

2. Unsupervised learning algorithms: Scikit-learn provides various unsupervised learning algorithms, such as clustering algorithms (e.g., k-means, DBSCAN) for grouping similar data points and dimensionality reduction techniques (e.g., PCA, t-SNE) for feature extraction and visualization.

3. Model selection and evaluation: Scikit-learn offers tools for model selection and evaluation, including techniques for cross-validation, hyperparameter tuning, and model performance metrics. It provides functions to split data into training and testing sets, assess model accuracy, and perform model selection based on different evaluation criteria.

4. Preprocessing and feature engineering: Scikit-learn includes preprocessing modules for handling common data preprocessing tasks, such as scaling, normalization, handling missing values, and encoding categorical variables. It also offers feature extraction techniques, such as text vectorization and feature selection methods.

5. Pipelines and model deployment: Scikit-learn supports building machine learning pipelines, which enable you to chain together multiple preprocessing and modeling steps. It also provides functionalities for saving and loading trained models for deployment in production environments.

Overall, scikit-learn is a powerful and versatile library that can be used for a wide range of machine learning tasks. It provides a consistent API and extensive documentation, making it accessible for both beginners and experienced practitioners.

In [64]:
from sklearn.linear_model import LinearRegression as prathamesh_LinerReg

In [65]:
Prathamesh_Model = prathamesh_LinerReg()
Prathamesh_Model

LinearRegression()

In [66]:
import numpy as prathamesh_np
from sklearn.model_selection import train_test_split
prathamesh_x, prathamesh_y = prathamesh_np.arange(20).reshape((10, 2)), range(10)
prathamesh_x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [67]:
list(prathamesh_y)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [68]:
x_train_prathamesh, x_test_prathamesh, y_train_prathamesh, y_test_prathamesh = train_test_split(prathamesh_x, prathamesh_y, test_size=0.33, random_state=30)

In [69]:
x_train_prathamesh

array([[12, 13],
       [ 8,  9],
       [14, 15],
       [16, 17],
       [18, 19],
       [10, 11]])

In [70]:
y_train_prathamesh

[6, 4, 7, 8, 9, 5]

In [71]:
x_test_prathamesh

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [72]:
y_test_prathamesh

[0, 1, 2, 3]

In [73]:
train_test_split(prathamesh_y,shuffle=False)

[[0, 1, 2, 3, 4, 5, 6], [7, 8, 9]]

In [74]:
Prathamesh_Model.fit(x_train_prathamesh, y_train_prathamesh)

LinearRegression()

In [75]:
prathamesh_predictions = Prathamesh_Model.predict(x_test_prathamesh)
prathamesh_predictions

array([3.44169138e-15, 1.00000000e+00, 2.00000000e+00, 3.00000000e+00])

## Conclusion:
In this practical we have learnt about scikit learn library and its features.