Prathamesh Ingale

# Practical 2

## Aim: 
Introduction to Python Programming: Learn the different libraries - NumPy, Pandas, SciPy, Matplotlib, Scikit Learn

## Theory:

### Numpy:
Numpy is a powerful numerical computing library for Python. It provides a high-performance multidimensional array object, as well as tools for working with these arrays. Numpy is widely used in the fields of data science, machine learning, and scientific computing, among others.

One of the primary features of Numpy is its ndarray (n-dimensional array) object. An ndarray is a homogeneous container for storing and manipulating large arrays of data, where each element has the same data type. These arrays can be of any dimensionality, from one-dimensional vectors to multi-dimensional matrices and tensors.

Numpy provides a rich set of functions for creating, manipulating, and performing mathematical operations on ndarrays. For example, ndarrays can be created using methods like np.array(), np.zeros(), and np.ones(). Arithmetic operations can be performed element-wise on ndarrays, and mathematical functions like np.sin(), np.cos(), and np.exp() can be applied to the elements of an array.

Numpy also includes tools for advanced indexing and slicing of ndarrays. Elements of an ndarray can be accessed and modified using indexing and slicing syntax, similar to that used for Python lists. However, Numpy allows for more advanced indexing techniques, such as integer and boolean indexing, and slicing with arbitrary step sizes.

Another key feature of Numpy is its ability to interface with other numerical computing libraries and languages, such as MATLAB and C. This makes it a popular choice for scientific computing and research, as it can be easily integrated into existing workflows and systems.

Overall, Numpy is a powerful and versatile library for numerical computing in Python, providing a comprehensive set of tools for manipulating and analyzing large arrays of data.

#### Few Methods in Numpy: 

1. array: The array method in numpy is used to create a multi-dimensional array. The method takes a Python list or tuple as input and converts it into a numpy array object. It can also take other array-like objects, such as pandas dataframes and lists of lists. The numpy array is a homogeneous data structure, meaning it can only contain elements of the same data type. This method is a fundamental tool for many numpy operations.

1. arange: The arange method is used to create a one-dimensional numpy array with a sequence of numbers. It works similarly to the built-in range function in Python. The method takes three arguments: start, stop, and step. The start argument is the first number in the sequence, stop is the last number in the sequence (not inclusive), and step is the spacing between the numbers in the sequence. If only one argument is provided, then it is interpreted as stop, and the default values for start and step are 0 and 1, respectively.

1. Ones and zeros: The ones and zeros methods in numpy are used to create arrays filled with either 0s or 1s, respectively. The methods take a shape tuple as input, which specifies the dimensions of the resulting array. For example, np.zeros((2,3)) creates a 2x3 array filled with 0s, while np.ones((3,3,3)) creates a 3x3x3 array filled with 1s.

1. linspace: The linspace method is used to create a one-dimensional numpy array with a specified number of evenly spaced numbers within a given interval. The method takes three arguments: start, stop, and num. The start argument is the first number in the sequence, stop is the last number in the sequence (inclusive), and num is the number of evenly spaced numbers in the sequence.

1. random: The random module in numpy provides a variety of methods for generating random numbers and arrays. Some of the most commonly used methods include random.rand, which generates a random array of a specified shape filled with numbers between 0 and 1, and random.randn, which generates a random array of a specified shape filled with numbers sampled from a standard normal distribution.

1. randint: The randint method in numpy is used to generate a random integer within a specified range. The method takes two arguments: low and high, which represent the lower and upper bounds of the range, respectively. If only one argument is provided, then it is interpreted as high, and the default value for low is 0.

1. randn: The randn method in numpy is used to generate a random array of a specified shape filled with numbers sampled from a standard normal distribution (i.e., a Gaussian distribution with mean 0 and variance 1).

1. reshape: The reshape method is used to change the shape of an existing numpy array. The method takes a shape tuple as input, which specifies the new dimensions of the array. The total number of elements in the new shape must be equal to the total number of elements in the original shape.

1. min, max, argmin, and argmax: The min, max, argmin, and argmax methods in numpy are used to find the minimum and maximum values in an array, as well as the indices ofthe minimum and maximum values. The min and max methods return the minimum and maximum values in the array, respectively. The argmin and argmax methods return the indices of the minimum and maximum values in the array, respectively.

1. Difference between min/max and argmin/argmax: The main difference between min/max and argmin/argmax is that the former return the actual minimum/maximum value(s) in the array, while the latter return the index/indices of the minimum/maximum value(s). In other words, min and max return a scalar value, while argmin and argmax return an integer or array of integers.

1. dtype: The dtype attribute in numpy is used to specify the data type of the elements in an array. The most common data types in numpy include int, float, bool, and string. The data type of an array can be specified when the array is created using the dtype argument, or it can be changed using the astype method. The dtype attribute can be used to access the data type of an existing array.

#### Brackets indexing and selection of elements
Bracket indexing and selection is a way to access and manipulate individual elements and subsets of elements in a NumPy array. Using bracket indexing, you can access individual elements of a one-dimensional or multidimensional array by specifying the index of the element within square brackets. If you want to select a subset of elements, you can use slicing notation with a colon to specify the range of indices to include.

When working with multidimensional arrays, you can use multiple indices separated by commas within the square brackets to access specific elements or subsets of elements. For example, to access the element in the second row and third column of a 2D array, you would use the indices \[1, 2\]. To select a subset of elements from the first two rows and the first two columns of the same array, you could use the slicing notation \[:2, :2\].

Bracket indexing and selection can be used to modify the values of elements within a NumPy array. By assigning a new value to a specific element or subset of elements, you can update the values stored in the array. This makes it possible to perform in-place modifications to the array, without having to create a new array and copy over values.

Overall, bracket indexing and selection is a powerful feature in NumPy that allows you to manipulate individual elements and subsets of elements in a NumPy array with ease.

#### Broadcasting
Broadcasting in NumPy is a powerful mechanism that allows for element-wise operations on arrays of different shapes and sizes. When two arrays are broadcast-compatible, NumPy will automatically perform the necessary transformations to make the operation possible.

The broadcasting rules in NumPy are as follows:

If the arrays do not have the same number of dimensions, NumPy will add dimensions to the smaller array until they match. For example, if you have a 1D array and a 2D array, NumPy will add a new axis to the 1D array to make it a 2D array that can be broadcast with the other array.

If the arrays have different sizes in a particular dimension, NumPy will stretch the smaller array along that dimension to match the larger array. For example, if you have a 2D array with shape (3, 4) and a 1D array with shape (4,), NumPy will stretch the 1D array along the first dimension to make it a 2D array with shape (3, 4) that can be broadcast with the other array.

If the arrays have different sizes in a particular dimension and neither size is equal to 1, NumPy will raise a "ValueError: frames are not aligned" error.
 
Broadcasting in NumPy can be a powerful tool for working with arrays of different shapes and sizes. By understanding the broadcasting rules and how they work, you can take advantage of this feature to write more concise and efficient code when working with NumPy arrays.

## Practical

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built in Methods

arange

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Zeros and Ones

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

LinSpace

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

eye

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random

In [16]:
np.random.rand(2)

array([0.31333719, 0.52721273])

In [17]:
np.random.rand(5,5)

array([[0.28184754, 0.28748955, 0.53185454, 0.7331353 , 0.75502424],
       [0.05393733, 0.22708958, 0.44690222, 0.21493791, 0.47139933],
       [0.90650604, 0.44177111, 0.25278716, 0.13186185, 0.53819083],
       [0.89611958, 0.50786272, 0.9587019 , 0.53400872, 0.11643094],
       [0.57532273, 0.28134532, 0.09905838, 0.69053731, 0.0460948 ]])

randn

returns a sample from the standard normal distribution

In [18]:
np.random.randn(3)

array([-0.42049377, -0.07942399,  0.43318574])

In [19]:
np.random.randn(5,5)

array([[ 2.47581121,  0.29029292, -1.09833828,  0.22941512, -0.37942044],
       [-1.58707468, -0.65689823,  0.71540684,  2.75250783, -1.65696881],
       [ 1.78164173, -0.43261332,  0.4372648 ,  0.77801166,  0.75453248],
       [ 0.41840454,  0.76977511, -1.64287339, -0.64676774,  0.86840188],
       [ 1.04741667, -1.22732562, -1.35510491, -1.50828265, -0.40980574]])

randint

In [20]:
np.random.randint(1,100)

56

In [21]:
np.random.randint(1,100,10)

array([35, 95, 98, 44,  5, 18, 26,  8, 13, 69])

Array Attributes and methods

In [22]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,100)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr

array([25, 41, 45, 11, 27, 30,  2, 12, 34, 48, 47, 26,  3, 35, 19, 31, 13,
       36, 18, 33, 31, 31, 26, 10,  2, 19, 36, 27, 39,  5, 48, 35, 21, 40,
       32, 25,  2, 35, 21, 39, 44,  8, 11, 46, 18,  4,  4, 27, 46, 35,  7,
       17, 40, 29, 19, 37, 36, 39,  4,  3, 30, 14, 15,  2,  2, 47, 44, 13,
        2, 28, 48, 10, 25,  9, 12, 47, 15, 12, 24, 22,  3, 22, 32, 32, 47,
       43, 27, 41, 40, 30, 39,  5, 41,  1, 12, 16, 35, 28, 17, 21])

Reshape

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

max,min,argmax,argmin

In [26]:
ranarr

array([25, 41, 45, 11, 27, 30,  2, 12, 34, 48, 47, 26,  3, 35, 19, 31, 13,
       36, 18, 33, 31, 31, 26, 10,  2, 19, 36, 27, 39,  5, 48, 35, 21, 40,
       32, 25,  2, 35, 21, 39, 44,  8, 11, 46, 18,  4,  4, 27, 46, 35,  7,
       17, 40, 29, 19, 37, 36, 39,  4,  3, 30, 14, 15,  2,  2, 47, 44, 13,
        2, 28, 48, 10, 25,  9, 12, 47, 15, 12, 24, 22,  3, 22, 32, 32, 47,
       43, 27, 41, 40, 30, 39,  5, 41,  1, 12, 16, 35, 28, 17, 21])

In [27]:
ranarr.max()

48

In [28]:
ranarr.min()

1

In [29]:
ranarr.argmax()

9

In [30]:
ranarr.argmin()

93

Shape

In [32]:
arr.shape

(25,)

In [33]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [34]:
arr.reshape(1,25).shape

(1, 25)

In [35]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

dtype

In [37]:
arr.dtype

dtype('int64')

### Numpy indexing and Selection

In [3]:
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

#### Brackets and indexing selection

In [4]:
arr[0]

0

In [5]:
arr[1:3]

array([1, 2])

In [6]:
arr[0:4]

array([0, 1, 2, 3])

In [7]:
arr[:4]

array([0, 1, 2, 3])

#### Broadcasting

In [8]:
arr[0:2]=500
arr

array([500, 500,   2,   3,   4])

In [9]:
arr=np.arange(0,19)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [10]:
slice_of_arr=arr[0:5]

slice_of_arr

array([0, 1, 2, 3, 4])

In [11]:
#changing slice

slice_of_arr [:]=55
slice_of_arr

array([55, 55, 55, 55, 55])

In [12]:
arr
# Elements will be modified as the elements in slice_of_arr are
# a reference to the original values of the array and not 
# a copy of the array.

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [13]:
# for copy we use arr.copy(), this allocates new memory for the data
arr_copy = arr.copy()
arr_copy

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

#### Indexing a 2D array (matrices)

In [14]:
arr_2d = np.array(([2,4,6],[8,10,12],[14,16,18]))
arr_2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

##### Getting a row of elements

In [15]:
arr_2d[1]

array([ 8, 10, 12])

##### getting a specific element

In [16]:
arr_2d[1][1]

10

In [17]:
##### Getting a specific element using comma notation

In [18]:
arr_2d[1,1]

10

##### 2D Array Slicing

In [19]:
arr_2d[:2,1:]
# upto 2 excluding 2 , all columns after 1 including 1 

array([[ 4,  6],
       [10, 12]])

In [20]:
arr_2d[:2,0:]

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [21]:
arr_2d[:2][0:]

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [22]:
arr_2d[2]

array([14, 16, 18])

In [23]:
arr_2d[1,:]

array([ 8, 10, 12])

#### Fancy Indexing

##### Set up a matrix

In [24]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
arr_length = arr2d.shape
arr_length

(10, 10)

In [30]:
arr_length = arr2d.shape[1]
arr_length

10

In [32]:
# in the zeroes array, we modify it using for loop
for i in range(arr_length): arr2d[i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows us the following

In [34]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [35]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

#### Selection

In [36]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr>6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [43]:
bool_arr = arr>4

In [44]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
x=2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Numpy Operations

In [48]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Basic Operators

In [50]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [54]:
arr/arr # Zero division Error

/tmp/ipykernel_640/188635853.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr # Zero division Error


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [55]:
1/arr # Zero division Error

/tmp/ipykernel_640/4171464411.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr # Zero division Error


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [56]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [57]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [58]:
arr**4

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

#### Universal Array Functions

In [59]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [60]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [61]:
np.max(arr)

9

In [62]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [63]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [64]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [68]:
np.tanh(arr)

array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997])

___

___

## NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

### Import NumPy as np

In [2]:
import numpy as np

### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

### Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

### Create an array of 10 fives

In [5]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

### Create an array of the integers from 10 to 50

In [6]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

### Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Create a 3x3 identity matrix

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### Use NumPy to generate a random number between 0 and 1

In [11]:
np.random.rand(1)

array([0.66149517])

array([ 0.42829726])

### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [12]:
np.random.randn(25)

array([ 0.50362292,  0.31234474,  1.45159233, -0.98572178,  2.08051079,
        0.95726019,  1.23406712, -2.16608289,  2.1196476 , -1.09796644,
        0.74950651, -1.21392959,  0.37913729, -0.41614333,  1.01231785,
        0.90271675, -0.44955753,  0.36491597,  0.61949714,  0.20563655,
       -0.34058509, -0.13243647,  0.72689362,  1.65962725,  0.7897242 ])

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

### Create the following matrix:

In [14]:
np.arange(0.01,1.01,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

### Create an array of 20 linearly spaced points between 0 and 1:

In [16]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

### Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [19]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [22]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[3][4]

20

20

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[:3][:,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [34]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[-1]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [36]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [37]:
mat.sum()

325

325

#### Get the standard deviation of the values in mat

In [38]:
mat.std()

7.211102550927978

7.2111025509279782

#### Get the sum of all the columns in mat

In [39]:
mat.sum(0) #  The zero value passed is given to the axis kwarg. 

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])

## Conclusion: 
I have successfully implemented different python libraries