In [10]:
import numpy as np #linear algebra
import pandas as pd #data processing
from sklearn.preprocessing import LabelEncoder #if data is string then use it to preprocess the data
from sklearn.tree import DecisionTreeClassifier

In [11]:
df = pd.read_csv('Stores.csv')
df.head()

Store ID   Store_Area  Items_Available  Daily_Customer_Count  Store_Sales
0          1        1659             1961                   530        66490
1          2        1461             1752                   210        39820
2          3        1340             1609                   720        54010
3          4        1451             1748                   620        53730
4          5        1770             2111                   450        46620

In [12]:
x = df[[ "Items_Available", "Daily_Customer_Count", "Store_Area"]]
y = df[["Store_Sales"]]

In [13]:
dt = DecisionTreeClassifier(criterion = "entropy")
dt

DecisionTreeClassifier(criterion='entropy')

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y,
test_size = .3, random_state = 0)
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
y_pred

array([ 69050,  33240,  35120,  37720,  38120,  64820,  86710,  46050,
        66020,  87330,  74330,  75530,  96610,  82940,  88270,  73170,
        62770,  68430,  36190,  44150,  77790,  56810,  71120,  76440,
        56830,  69370,  50950,  73800,  45720,  51700,  64950,  54650,
        74520,  55390,  38120,  58390,  75300,  49210,  41500,  72410,
        50680,  89760,  77080,  39650,  81370,  39200,  78130,  36280,
        78060,  54200,  52780,  79760,  64670,  64640,  41080,  78090,
        87890,  81390,  94370,  62960,  79780,  68390,  76250,  75120,
        82020,  56010,  74080,  56010,  85130,  49070,  84360,  39460,
        73120,  71240,  38530,  41080,  59760,  76530,  87330,  73590,
        73170,  82270,  48300,  41080,  45940,  51850,  70450,  67290,
        35280,  39730,  42880,  49210,  89760,  46040,  89760,  51950,
        46100,  56810,  41740,  57140,  69090,  49540,  42890,  60940,
        61660,  60440,  41080,  46100,  80970,  65080,  78060,  53760,
      

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0
for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the ID3 is: ', corrPred/(cm.sum()))

Correct predictions:  0
False predictions 269


Accuracy of the ID3 is:  0.0


In [20]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text

In [21]:
iris = load_iris()

In [22]:
decision_tree = DecisionTreeClassifier(random_state=0, max_depth=2)
decision_tree = decision_tree.fit(iris.data, iris.target)

In [23]:
r = export_text(decision_tree,
feature_names=iris['feature_names'])
print(r)

|--- petal width (cm) <= 0.80
|   |--- class: 0
|--- petal width (cm) >  0.80
|   |--- petal width (cm) <= 1.75
|   |   |--- class: 1
|   |--- petal width (cm) >  1.75
|   |   |--- class: 2



In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from sklearn.datasets import load_iris
iris = load_iris()

In [ ]:
X = iris.data
y = iris.target
dataset = pd.read_csv('Golf.csv')

In [ ]:
dataset.head()

In [ ]:
# splitting X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
test_size=0.4, random_state=1)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
# training the model on training set
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

In [ ]:
y_pred = gnb.predict(X_test)
print(y_pred)

In [ ]:
# comparing actual response values (y_test) with predicted response values (y_pred)
y_compare = np.vstack((y_test,y_pred)).T
y_compare[:5,:]

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

In [ ]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0
for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ', corrPred/(cm.sum()))