### Numpy indexing and Selection

#### Brackets indexing and selection of elements
Bracket indexing and selection is a way to access and manipulate individual elements and subsets of elements in a NumPy array. Using bracket indexing, you can access individual elements of a one-dimensional or multidimensional array by specifying the index of the element within square brackets. If you want to select a subset of elements, you can use slicing notation with a colon to specify the range of indices to include.

When working with multidimensional arrays, you can use multiple indices separated by commas within the square brackets to access specific elements or subsets of elements. For example, to access the element in the second row and third column of a 2D array, you would use the indices \[1, 2\]. To select a subset of elements from the first two rows and the first two columns of the same array, you could use the slicing notation \[:2, :2\].

Bracket indexing and selection can be used to modify the values of elements within a NumPy array. By assigning a new value to a specific element or subset of elements, you can update the values stored in the array. This makes it possible to perform in-place modifications to the array, without having to create a new array and copy over values.

Overall, bracket indexing and selection is a powerful feature in NumPy that allows you to manipulate individual elements and subsets of elements in a NumPy array with ease.

#### Broadcasting
Broadcasting in NumPy is a powerful mechanism that allows for element-wise operations on arrays of different shapes and sizes. When two arrays are broadcast-compatible, NumPy will automatically perform the necessary transformations to make the operation possible.

The broadcasting rules in NumPy are as follows:

If the arrays do not have the same number of dimensions, NumPy will add dimensions to the smaller array until they match. For example, if you have a 1D array and a 2D array, NumPy will add a new axis to the 1D array to make it a 2D array that can be broadcast with the other array.

If the arrays have different sizes in a particular dimension, NumPy will stretch the smaller array along that dimension to match the larger array. For example, if you have a 2D array with shape (3, 4) and a 1D array with shape (4,), NumPy will stretch the 1D array along the first dimension to make it a 2D array with shape (3, 4) that can be broadcast with the other array.

If the arrays have different sizes in a particular dimension and neither size is equal to 1, NumPy will raise a "ValueError: frames are not aligned" error.
 
Broadcasting in NumPy can be a powerful tool for working with arrays of different shapes and sizes. By understanding the broadcasting rules and how they work, you can take advantage of this feature to write more concise and efficient code when working with NumPy arrays.

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

#### Brackets and indexing selection

In [3]:
arr[0]

0

In [4]:
arr[1:3]

array([1, 2])

In [5]:
arr[0:4]

array([0, 1, 2, 3])

In [6]:
arr[:4]

array([0, 1, 2, 3])

#### Broadcasting

In [7]:
arr[0:2]=500
arr

array([500, 500,   2,   3,   4])

In [8]:
arr=np.arange(0,19)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [9]:
slice_of_arr=arr[0:5]

slice_of_arr

array([0, 1, 2, 3, 4])

In [10]:
#changing slice

slice_of_arr [:]=55
slice_of_arr

array([55, 55, 55, 55, 55])

In [11]:
arr
# Elements will be modified as the elements in slice_of_arr are
# a reference to the original values of the array and not 
# a copy of the array.

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [12]:
# for copy we use arr.copy(), this allocates new memory for the data
arr_copy = arr.copy()
arr_copy

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

#### Indexing a 2D array (matrices)

In [14]:
arr_2d = np.array(([2,4,6],[8,10,12],[14,16,18]))
arr_2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

##### Getting a row of elements

In [15]:
arr_2d[1]

array([ 8, 10, 12])

##### getting a specific element

In [16]:
arr_2d[1][1]

10

In [19]:
##### Getting a specific element using comma notation

In [20]:
arr_2d[1,1]

10

In [21]:
arr_2d[:2,1:]

array([[ 4,  6],
       [10, 12]])